import type { StudyResource } from "@/types/resource";

export const seedResources: StudyResource[] = [
  {
    id: "r1",
    title: "SPM Trial Add Maths 2024 - Johor",
    subject: "Additional Mathematics",
    category: "trial_paper",
    form_level: 5,
    year: 2024,
    file_url: "#",
    uploaded_by: "teacher@moe-dl.edu.my",
    created_at: "2026-03-01T09:00:00.000Z",
    downloads: 184,
  },
  {
    id: "r2",
    title: "Form 3 Science Notes - Chapter 6",
    subject: "Science",
    category: "notes",
    form_level: 3,
    year: 2025,
    file_url: "#",
    uploaded_by: "student@moe-dl.edu.my",
    created_at: "2026-03-12T11:30:00.000Z",
    downloads: 92,
  },
  {
    id: "r3",
    title: "SPM Sejarah Past Year 2023",
    subject: "Sejarah",
    category: "past_year_paper",
    form_level: 5,
    year: 2023,
    file_url: "#",
    uploaded_by: "alumni@moe-dl.edu.my",
    created_at: "2026-02-16T10:15:00.000Z",
    downloads: 240,
  },
  {
    id: "r4",
    title: "Form 2 Mathematics Trial Set",
    subject: "Mathematics",
    category: "trial_paper",
    form_level: 2,
    year: 2024,
    file_url: "#",
    uploaded_by: null,
    created_at: "2026-03-17T14:10:00.000Z",
    downloads: 63,
  },
  {
    id: "r5",
    title: "English Writing Notes - SPM",
    subject: "English",
    category: "notes",
    form_level: 5,
    year: 2025,
    file_url: "#",
    uploaded_by: "mentor@moe-dl.edu.my",
    created_at: "2026-02-25T08:45:00.000Z",
    downloads: 108,
  },
  {
    id: "r6",
    title: "Form 4 Biology Past Year 2022",
    subject: "Biology",
    category: "past_year_paper",
    form_level: 4,
    year: 2022,
    file_url: "#",
    uploaded_by: "teacher2@moe-dl.edu.my",
    created_at: "2026-01-20T08:00:00.000Z",
    downloads: 76,
  },
  {
    id: "r7",
    title: "Form 1 BM Notes - Tatabahasa",
    subject: "Bahasa Melayu",
    category: "notes",
    form_level: 1,
    year: 2025,
    file_url: "#",
    uploaded_by: null,
    created_at: "2026-03-19T16:00:00.000Z",
    downloads: 45,
  },
];
